on:
  push:
    branches: [ master ]

name: ğŸš€ Deploiement du site automatique
jobs:
  web-deploy:
    name: ğŸ‰ Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Recuperer le code le plus rÃ©cent
      uses: actions/checkout@v2.3.2

    - name: ğŸ“‚ Synchroniser les fichiers
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.ftp_server }}
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        port: ${{ secrets.ftp_port }}
        server-dir: ${{ secrets.ftp_serverdir }}
        exclude: .git*
          - .git*/**
          -  **/.git*/**
          - README.md
